SOLUTIONS/Find Sum square Difference.cpp

C plus plus solution for issue #1

add Find Sum square Difference solution in cpp

---

ASSIGNMENTS/Hello World.java
SOLUTIONS/Hello World.java

Add file to solutions folder

---

SOLUTIONS/helloworld.c

added hello world in c language
https://github.com/hackerearthclub/CODE2RACE/issues/7

helloworld.c : helloworld added

---

HelloWorld.js

Created Hello world message in JS.
issue #7

Created Hello world message in JS.

---

SOLUTIONS/HelloWorld.asm

Added HelloWorld in Assembly

---

SOLUTIONS/HelloWorld-hacktoberfest.cpp

Create HelloWorld-hacktoberfest.cpp - Doan Ngoc Huan

---

SOLUTIONS/hello_world.vbs

Added vbscript hello world

---

SOLUTIONS/sum -Factorial digit.py

add python solution for sum -Factorial digit

---

SOLUTIONS/Circular_Primes.js

Usage: node Circular_Primes.js N

add circular primes in javascript

---

SOLUTIONS/Hello world.go

Hello world in Golang

---

SOLUTIONS/HelloWorld.swift

Added Swift

---

SOLUTIONS/sumFactorialDigits.cpp

sumFactorialDigits - Doan Ngoc Huan

---

SOLUTIONS/Sum Factorial Digit.py

Submitting solution for #9 in python

Sum factorial solution in python

---

SOLUTIONS/helloWorld.R

PLEASE review and merge my changes

Added R programming language HELLO WORLD

---

SOLUTIONS/CircularPrime.cpp

#15 Add Circular Primes in C++

Add Circular Primes in C++

---

SOLUTIONS/HelloWorld.m

HelloWorld in Objective C

---

OPEN CHALLENGE/fruitDetection.py

This is a fruit detection algorithm using Python-OpenCV.

Fruit detection algorithm

---

SOLUTIONS/HelloWorld.cs

Added hello world solution in C#

---

SOLUTIONS/nfibonac.cpp

nfibonac.cpp

---

SOLUTIONS/hello_world.php
SOLUTIONS/hello_world.pl

Hello world in perl

---

SOLUTIONS/evenFiboonacciNumbers.cpp

Create evenFiboonacciNumbers.cpp - Doan Ngoc Huan

---

SOLUTIONS/reverse-word.py

Solved:
https://github.com/bgail/CODE2RACE/blob/master/ASSIGNMENTS/reverse-word

added python solution for reverse-word

---

SOLUTIONS/readfile.py
SOLUTIONS/sample.txt

-readfile.py
-sample.txt for sample textfile

added reaadfile solution

---

OPEN CHALLENGE/roll_dice.py

A dice rolling script that uses RegEx to intuitively roll dice. Instructions are at the top of the script. Adapted from a discord bot I previously wrote to do this.

Open Challenge: Dice Roller

---

COMPETITORS/competitors.md
SOLUTIONS/octal_decimal.py

OctalDecimal [PYTHON] -Matteo Veraldi

---

SOLUTIONS/helloWorld.kt

Kindly review my changes and merge them

Added hello World in KOTLIN

---

SOLUTIONS/lcm_gcd.py

I created two functions to calculate the gcd and lcm of two numbers and then used those to calculate the gcd and lcm of an array #113

Add Solution to LCM and GCD of array of numbers in Python 

---

SOLUTIONS/Rock_Paper_Scissor.java

A rock ,paper and scissors game written in java !

Rock ,Paper and Scissors in java

---

OPEN CHALLENGE/helloworld.php
OPEN CHALLENGE/hellworld.php

I created "Hello world" with html/php

Hello world php version

---

SOLUTIONS/helloworld.py

Hi! Just added another pythonscript, don't know if you accept duplicates

Add a hello world written in python, task #7

---

SOLUTIONS/sumDoublyLinkedList.java

Added sumDoublyLinkedList.java

---

SOLUTIONS/rock-paper-scissors.py

Added rock-paper-scissors.py to SOLUTIONS for issue #68

Issue#68 solved

---

SOLUTIONS/ReadFile.py
SOLUTIONS/sum_doubly_linked_list.py

Sum doubly linked list

---

SOLUTIONS/ACIIIProduct.py

Solves #108 
Please review the changes.

Implemented ACIIIproduct.txt in python3

---

SOLUTIONS/DiagonalBinaryTree.py

Does it in O(N) time and space where N is the number of nodes
Edit: Solves #112

Prints binary tree in a diagonal manner

---

SOLUTIONS/LengthofLargestSub_Array.py

Developed a solution for identifying the largest sub-array containing more primes than non-primes.

Find Length of largest sub-array having primes strictly greater than non-primes #114

---

SOLUTIONS/ReadFile.py
SOLUTIONS/sum_doubly_linked_list.py

Added Read file

---

SOLUTIONS/findASCIIvalue.java

dropped the findASCIIvalue.java file in SOLUTIONS directory

submitted solution file to SOLUTIONS subdirectory as per #108

---

SOLUTIONS/LCM__GCD.cpp

Program to find the LCM and GCD of an array.
Written in C++.
Please merge the program.

LCM and GCD of an array

---

SOLUTIONS/Hello_World.java

Hello world - in Java

---

SOLUTIONS/BirthdayTreat.java

Problem referenced in Issue #111. Solution runs in O(N).

Birthday Treat

---

SOLUTIONS/Product-of-ASCII-VALUES-OF-STRING

java program to calculate product of ASCII values of characters of a string

Product-of-ASCII-VALUES-OF-STRING

---

OPEN CHALLENGE/dynamicArray.c

Added a solution to https://www.hackerrank.com/challenges/dynamic-array-in-c/problem

Added Solution to HackerRank Dynamic Array in C problem

---

SOLUTIONS/waitForIt.cpp

Create waitForIt.cpp - Doan Ngoc Huan

---

SOLUTIONS/BirthdayPartyProblem.py

Runs in O(N+Q) where N is the number of guests and Q is the number of queries.  Also added input parsing and argument handling.
Resolves #110

Added a solution to the Birthday Party Scheduling problem

---

Hello World
Hello%20World[1]
SOLUTIONS/lcm_gcd[1].py
SOLUTIONS/lcm_gcd[2].py
hacktoberfest open challenge
lcm.py
lcm[1].py
lcm_gcd.py
rockpaperscissors.py
rockpaperscissors[1].py

 Hello World in python

---

SOLUTIONS/JavaEmailer

This class can be used in conjunction with the Java Mail to send emails from your application.

Java Email class

---

SOLUTIONS/sumofnum.py
SOLUTIONS/uppercase.py

Python program for upper case conversion and sum of numbers

Upper case and sum of numbers

---

SOLUTIONS/ASCIICODE.PY

PRODUCT OF ASCII CODES OF EACH CHARACTER IN A STRING

Add files via upload 

---

OPEN CHALLENGE/Plot.py

Environment Setup:
``` pip install numpy```
```pip install matplotlib```
Refer #60 #165

Added Sine/Cosine Ploting using Matplotlib

---

SOLUTIONS/ATMproblem.cpp

add ATMproblem solution

---

OPEN CHALLENGE/largest_unique_substr.py

largestunique substring in a given substring

---

OPEN CHALLENGE/D3 Visualisation/data-02.json
OPEN CHALLENGE/D3 Visualisation/data.json
OPEN CHALLENGE/D3 Visualisation/index.html
OPEN CHALLENGE/D3 Visualisation/network.css
OPEN CHALLENGE/D3 Visualisation/network.js

Adding a D3 Network Visualisation page. Index.html can be opened locally to view the D3 page in action.

Added D3 Visualisation network

---

SOLUTIONS/ATM_problem.c

Solution to ATM problem #181 in C 

---

SOLUTIONS/atm-solution.py

Adding solution for atm problem in python.

Add ATM problem solution in python

---

SOLUTIONS/Factorize.cpp

Create Factorize.cpp - Doan Ngoc Huan

---

ASSIGNMENTS/lcm_gcd.txt
SOLUTIONS/helloWorld.kt

A python file containing the code to find the lcm and gcd of an array of number.

Added a file containing code to find the lcm and gcd of an array of number #113

---

SOLUTIONS/Hello world.sh
SOLUTIONS/Pandigital prime.c

Add | Diego Bernal

---

ASSIGNMENTS/Empty Bottles.txt
OPEN CHALLENGE/HighestFrequency.java

The program is much more efficient and user friendly in taking out and displaying the highest frequency of the alphabet in the string as instead of using and creating frequency array we use HashMap which is much faster and efficient than arrays.

Finding the alphabet with the highest frequency.

---

SOLUTIONS/HelloWorldJava.java

Solution for HelloWorld in Java

---

OPEN CHALLENGE/graphs.py

Visualize tahn, sigmoid, and relu graphs.  
Helps to understand activation functions in deep learning.
Issue #165

Tahn, Sigmoid and ReLU graphs

---

SOLUTIONS/ATM_problem.cpp

Added atm problem

---

SOLUTIONS/digits_removal_and_div.cpp

issue - #165 
this is solution to the problem : 
https://codeforces.com/problemset/problem/550/C
It got accepted

code to check whether a number could be made to be divisible by 8 after removing a few digits

---

SOLUTIONS/Number_game_in_c++.txt

here is the solution of number game problem in c++

solution of number game problem

---

SOLUTIONS/pandigitalPrime.cpp

Create pandigitalPrime.cpp - Doan Ngoc Huan

---

SOLUTIONS/ASCIIProduct.js
SOLUTIONS/reverse-word.js

Added solutions to:-
ASCIIproduct
ReverseWord

solved ascii-product, reverse word using javascript

---

SOLUTIONS/countCap.py

My shot at this assignment, using as if it is a factorial conversion
issue #240

Count Capacitors

---

OPEN CHALLENGE/p2.c

c program file to print pyramid

pyramid pattern

---

OPEN CHALLENGE/radixSortMSB.py

Added Radix sort code -Most significant bit in python https://github.com/hackerearthclub/CODE2RACE/issues/165

Radix sort MSB python #165 

---

SOLUTIONS/helloworld_js_and_html.html

The page opens and a JS alert pop-up is shown.
Ref #7

Adding HelloWorld solution in HTML and JS

---

SOLUTIONS/HelloWorld.clj

solve "Hello, World!" problem #7

Added hello world in Clojure

---

SOLUTIONS/CALENDER.PY
SOLUTIONS/Counting_Capacitors.py
SOLUTIONS/HELLO_WORLD.cpp
SOLUTIONS/HelloWorld.kt
SOLUTIONS/LCM.py
SOLUTIONS/ReadFile.py
SOLUTIONS/RockPaperScissors.py

My solution file name is Counting_Capacitors.py .

Solution to count capacitors problem.

---

SOLUTIONS/Pandigital Prime.py

Empty Bottles in Python 3

---

SOLUTIONS/JavaHelloWorldProblem.java

Made a solution for the "Hello World" problem in java.

Created a solution for my problem

---

COMPETITORS/competitors.md
SOLUTIONS/hello_world.java

Signed-off-by: felixfaker <faizaan.mm@gmail.com>

[Add] - [Mohammed Faizaan ]

---

SOLUTIONS/hello world.bat

Added hello world in DOS

---

OPEN CHALLENGE/hellworld.php

Added DOCTYPE

---

SOLUTIONS/SumFactorialDigit.go

Solution to the SumFactorialDigits problem written in Golang.

Solution for SumFactorialDigits in Golang

---

SOLUTIONS/triominoes.py

- By generating states row by row, then only the next two rows could be affected.
- Making use of this fact, we store all the possible states and process them only once (**dynamic programming approach**).
- It is very important to note that the number of columns should be the min of n and m.
- The number of possible states = 2^(6 * 2) * 41 = 167,936 which is very pleasant.
- The current average time taken per input is **0.02497931990292993 seconds.**
- I've added a naive solution using brute force so I could test my solution against it with small random data.
- I've added benchmarks against big random data.
[issue#241](https://github.com/hackerearthclub/CODE2RACE/issues/241)

Added a solution for the triominoes, issue#241

---

SOLUTIONS/darts_solution.py

Solving #298 
It seems I understand rules of the game wrong

Solve Darts

---

SOLUTIONS/FindFactors.go

This piece of code calculates all valid factors of a given number. It is written in GoLang!

Created factors.go

---

SOLUTIONS/Reverse_word.java

answer to the Reverse-Word question

Update and rename ReverseWord.java to Reverse_word.java

---

SOLUTIONS/EmptyBottle.py
SOLUTIONS/ReverseDict1.py

python code to findout the filled bottle after all transformation

created EmptyBottle.py

---

OPEN CHALLENGE/sigmoid_graph.py

adding sigmoid graph example file

create sigmoid_graph example file

---

SOLUTIONS/DiagonalBinaryTree.cpp

[https://github.com/hackerearthclub/CODE2RACE/blob/master/ASSIGNMENTS/DiagonalBinaryTree.pdf](url)

Traverse Binary Tree Diagonally

---

SOLUTIONS/Hello_world_python.py

adding hello world python script

create hello world pyton script

---

SOLUTIONS/ATM_SOLUTION.py

ATM_SOLUTION.py: Typo in variable name

---

SOLUTIONS/ASCII2.py

ASCII2.py: Works on Python and legacy Python

---

SOLUTIONS/lcm.py

lcm.py: Comment out Python syntax errors

---

SOLUTIONS/rock-paper-scissors.py

rock-paper-scissors.py: Works on Python and legacy Python

---

OPEN CHALLENGE/rsa.py

rsa.py: : Works on Python and legacy Python

---

ASSIGNMENTS/allocate_servers.txt
ASSIGNMENTS/grid_illumination.txt
SOLUTIONS/allocate_servers_sol.py
SOLUTIONS/grid_illumination_sol.py

Example of a good interview problem

Add two problems w/ solutions #165

---

SOLUTIONS/hello_world.rs

Add hello-World in Rust. Greetz from Bochum Germany. Thx for the practice opportunity

add hello world in Rust to Solutions subdirectory

---

SOLUTIONS/OctalDecimal.js
SOLUTIONS/hello_world.hs

Here's my solution in JS ES6 to the octal-decimal conversor problem
( issue #62, described [here](https://github.com/hackerearthclub/CODE2RACE/blob/master/ASSIGNMENTS/OctalDecimal) )

OctalDecimal solution in JS ES6

---

SOLUTIONS/helloworld.py
lcmcode.py
tests/test_hello.py

Fixes #393.  Run PyTests on both SOLUTIONS and OPEN CHALLENGE.

Travis CI: Start testing OPEN CHALLENGE too

---

OPEN CHALLENGE/face-detection/Cascades/haarcascade_eye.xml
OPEN CHALLENGE/face-detection/Cascades/haarcascade_frontalface_default.xml
OPEN CHALLENGE/face-detection/facedetection.py

issue #165 
Added code to detect faces in live video feed

added face detection code

---

SOLUTIONS/OctalDecimal.go

Completed the solution for Assignment OctalDecimal in Golang

Solution for OctalDecimal converter in Golang added

---

SOLUTIONS/HelloWorld.f08

Hello world in Fortran.

---

.travis.yml

Another attempt at #391 
We need help from some experts in C/C++, Java, JavaScript to adjust the config for their language of choice. It would be good to get some basic linting (ESlint, etc.) going and then some regular tests as well. Other languages are welcome.
You help is appreciated.

Travis CI: Parallel tests for Python, C/C++, Java, JavaScript

---

SOLUTIONS/Reverse-Word1.py

Added Reverse-Word1.py to solve reverse-word.md challenge.

Added Reverse-Word1.py to Solutions

---

ASSIGNMENTS/fizzBuzz.js

fizzBuzz.js

---

OPEN CHALLENGE/CurrencyFormatterToIDR

CurrencyFormatter To IDR

---

OPEN CHALLENGE/JavaScript-Sync-Delay.js

Added a [Right way of delaying execution synchronously in JavaScript without using Loops or Timeouts!](https://blog.praveen.science/right-way-of-delaying-execution-synchronously-in-javascript-without-using-loops-or-timeouts/)

JavaScript Synchronous Delay

---

OPEN CHALLENGE/ReadWriteDel.go

added new golang program

---

SOLUTIONS/Mystery.py

Mystery solution in python

---

SOLUTIONS/hello_world_python.py

Hello World in Python: hackerearthclub#7

Hello World in Python: hackerearthclub#7

---

OPEN CHALLENGE/concurrentTennisSimulator.go

Code for issue: 'Hacktober-Fest-Challenge- ANY CODE IN ANY LANGUAGE'.

Adding a Concurrent Tennis Simulator on Go lang. Let's Hack.

---

SOLUTIONS/tree when given infix and prefix

Create tree when given infix and prefix

---

SOLUTIONS/Binary Multiple of 3.c

Binary Multiple of 3 in C!

---

SOLUTIONS/Mystery2.java

Add Mystery solution in java

---

SOLUTIONS/NthPowerOfDigit

https://github.com/hackerearthclub/CODE2RACE/commit/2bab13069940ef28c61f43b07516718fff4698fb

NthPowerOfDigit.py

---

SOLUTIONS/BinaryMultipleOfThree.java

Binary Multiple of 3

---

SOLUTIONS/reverse_word.rb

Ruby program to reverse words.

Reverse word in ruby

---

SOLUTIONS/binary_multiple_3.py

add solution to binary multiple of 3

---

Hello_World(in_C++).cpp

Hello World Code in C++ language.

Hello_World(in_C++).cpp

---

OPEN CHALLENGE/Count_No._Of_Zeros.cpp

C++ code to count number of zeroes in the factorial of inputted number.

Count_No._Of_Zeros.cpp

---

SOLUTIONS/Magic_no.cpp

Issue #165 for hackoctober fest

---

SOLUTIONS/Binary Multiple of 3.py

solution for Binary Multiple of 3

Create Binary Multiple of 3.py

---

COMPETITORS/competitors.md
SOLUTIONS/Find_the_sum_square_difference.py

I did not use any loop for finding squares or sum. Coded in Python.

Added solution to finding sum square difference

---

SOLUTIONS/SUMSQUAREDIFF

https://github.com/hackerearthclub/CODE2RACE/commit/e820acad34beb2f46c238355f8e6d61ec9b28b76

SUMSQUAREDIFF

---

ASSIGNMENTS/EverWordCasedString.md
SOLUTIONS/EverWordCasedString.py

Reverts hackerearthclub/CODE2RACE#522

Revert "Add new assignment 'EverWordCasedString'"

---

SOLUTIONS/Factorize_problem.cpp

Added Solution to the Factorize Problem

---

SOLUTIONS/Hello_World_cpp14.cpp

code to print Hello, World! in cpp

Added code for Hello World in cpp

---

SOLUTIONS/LargestSubarrayPrime.py

Solution for #114 
The python script is well documented, in case someone is interested in the algorithm, it can be checked there.

added LargestSubarrayPrime solution in python

---

SOLUTIONS/decimal_octal_conversion.rb

Ruby implementation for conversion.

Decimal to octal and octal to decimal conversion

---

Hello world.cpp
OPEN CHALLENGE/HELLO WORLD.cpp

Hello World in C++

---

SOLUTIONS/ACIIIproduct.py

Solution to the ACIIIproduct problem made in Python

ACIIIproduct

---

ASSIGNMENTS/bfs_spanni_tree

bfs_spanni_tree level based spannig tree

bfs_spanni_tree

---

SOLUTIONS/ascii1product.py

solution of ascii1product in python 3

create  ascii1product.py

---

SOLUTIONS/sum--factorial digit.py

simple solution of sum--factorial digit in python 3

create sum--factorial digit.py

---

ASSIGNMENTS/A Game of Robots.md
ASSIGNMENTS/Reduction Game.md

<b> added two question </b>
- A game of robots
- Reduction game

Added two questions

---

SOLUTIONS/hello-world.java

A simple program to represent interaction using Scanner class

Add the new program

---

OPEN CHALLENGE/AzureHack.ps1

Added a small hack around Azure

Added some Powershell

---

SOLUTIONS/HelloWorld__SagarSuri.cpp

complete assignment helloworld.md

surisagar900

---

COMPETITORS/competitors.md
SOLUTIONS/Hello_World.html

Kindly check it and star my repository.

Problem no. 19 solved by AMAN NIM

---

SOLUTIONS/BinaryMultipleOf3.cpp

solved binary multiple of 3 in cpp

---

SOLUTIONS/reverse-word-in-sentence.js

Added solution for reversing a word in javascript

Added solution for  reverse word in javascript

---

SOLUTIONS/palindrome.js
SOLUTIONS/reverse-word-in-sentence.js

Solved the Palindrome problem #577

---

SOLUTIONS/ACIIIProduct.py

most of the newbies run code in Python 3.x versions.

update the comment name for code

---

SOLUTIONS/reduction game

reduction game solution

---

SOLUTIONS/chetan gaur

added a basic C code for beginners

Create chetan gaur

---

ASSIGNMENTS/ReductionGame.py

Made for the Issue:
Solve Reduction Game #573
https://github.com/hackerearthclub/CODE2RACE/issues/573

Created ReductionGame.py

---

SOLUTIONS/helpKatekar.py

Solution to Issue #571 HelpKatekar, written in Python3.
Input expected in format
N
n1 n2 n3 ... nN

Solution to help Katekar problem

---

SOLUTIONS/Game Of Robots

Solution Of Game Of robots

---

OPEN CHALLENGE/robotgame.cpp

Solve Game of Robots

---

OPEN CHALLENGE/MathPractice.java

This program is geared towards elementary students that would seek to practice their math skills outside the class. The program generates two random numbers to generate an equation. When working with subtraction the program works to ensure there is no negatives and with division there is no dividing by zero.

Math Practice

---

SOLUTIONS/Palindrome.java

Created Palindrome.java

---

SOLUTIONS/readFile-paolaguarasci.cpp

This program takes the file path from the command line, reads it and returns the content to the video.

readFile and cmd line args

---

SOLUTIONS/vertumnoACIIIProduct.py

Adding my solution in Python to the ACIII Product assignment.

ACIII Product assignment.

---

OPEN CHALLENGE/parlindrome.js

i was able to determine if a word is parlindrome or not using the reduce method

i solved the parlindrome challenge

---

SOLUTIONS/A_Game_Of_Robots.py

Solution of A Game of Robots in Python 3

---

ASSIGNMENTS/ATM problem.md

The compatibility problems in a ATM machine makes problems to normal banking users those who are not aware of the machine's working.

Compatibility in ATM

---

SOLUTIONS/reverse-Word-Python.py

Just added a solution for reverse a word in python

solution for reverse a word in python lang

---

SOLUTIONS/asciipro.py
SOLUTIONS/atm_machine.py
SOLUTIONS/binary_3.py

Signed-off-by: Ritesh <rk301999@gmail.com>

atm machine and ascii pro

---

SOLUTIONS/VideoPosts.java

naive solution to video posts in Java

VideoPosts.java

---

OPEN CHALLENGE/MO_ALGO.cpp

MO Algorithm can be used on trees to answer queries offline.

Added MO Algorithm on Trees Code in C++

---

COMPETITORS/competitors.md

Added myself as a participant.

[Add] - [Amulya Gaur]

---

SOLUTIONS/A game of robots.cpp

Solution to '[A Game of Robots](https://github.com/hackerearthclub/CODE2RACE/blob/master/ASSIGNMENTS/A%20Game%20of%20Robots.md)' in CPP.

A Game of Robots in CPP

---

SOLUTIONS/Palindrome_check_for_word.py

This is solution in python 3.6

Palidrome.py

---

OPEN CHALLENGE/sudokusolver.cpp
OPEN CHALLENGE/water_jug.py

Sudoku Solver in C++

---

OPEN CHALLENGE/palidromo.c

Verify if is a palidrome word

---

OPEN CHALLENGE/Roman Numeral Converter.js

A program to convert a number to its Roman numeral equivalent.

Add Roman Numeral Converter

---

ASSIGNMENTS/SwimmingPool.md

SwimmingPool.md

---

SOLUTIONS/NthPowerOfDigit.cpp

added fast exponentiation

---

SOLUTIONS/questionforpractice.c

Created a solution for Question for practice

---

OPEN CHALLENGE/MillerRabin.cpp

Miller Rabin algorithm can be used for prime checking in O(logn) for numbers upto 10^18

Added Miller Rabin Algorithm code for prime checking

---

OPEN CHALLENGE/Special Pythagorean triplet

I've solved this for Project Euler in C++;
The problem sounds like this:
A Pythagorean triplet is a set of three natural numbers, a < b < c, for which a2 + b2 = c2
There exists exactly one Pythagorean triplet for which a + b + c = 1000.
Find the product abc.

special pythagorean triplet problem

---

SOLUTIONS/BeginnersProblem2.java

#682 (https://github.com/hackerearthclub/CODE2RACE/issues/682) Java Solution

Solution for Beginners Problem 2.0

---

SOLUTIONS/beginersProblem.py

solution to problem announced in Issue #682 .

Solution to beginners' problem 2.0

---

SOLUTIONS/gcd_array.py

GCD of array in pyhton3 added

---

OPEN CHALLENGE/sum-of-multiples.cpp

How i solved the first problem on projecteuler.net

sum of all the multiples of 3 or 5 below 1000

---

SOLUTIONS/begprob2.py

solution to beginner problem 2.0 issue #682

---

SOLUTIONS/binary_multiple_of_3.js

Signed-off-by: Szabolcs Nagy <snagy@wcl.american.edu>

solved binary multiple of 3 with javascript/node

---

SOLUTIONS/robo.cpp
solution_hw.py

this is my code for Robo Game Solution in C++ language.

RoboGameSolution

---

ASSIGNMENTS/Don't Jump.md

Added Don't  Jump

---

.idea/vcs.xml
SOLUTIONS/prob_fizz_buzz.py

Feat/solve advanced prob fizz buzz #681

---

SOLUTIONS/Advanced prob_FizzBuzz.py

Simple python solution to #681, Advanced prob_FizzBuzz

Create Advanced prob_FizzBuzz.py (Solves #681)

---

SOLUTIONS/UnusualGame.ipynb

I'm a beginner here. I'm trying to solve the issue #679, Unusual Game

Unusual Game (Solves #679)

---

OPEN CHALLENGE/Hello.js

added my javascript ES6 code

---

SOLUTIONS/beginers_problem.py

I have uploaded the solution to beginners problem in the solutions folder as beginners_problem.py ,as the filetype suggest it is for python.

The solution to the beginners problem

---

SOLUTIONS/Beginners_Problem2.py

Simple python code for "Beginners Problem 2.0"

Create Beginners Problem 2.0 in python

---

SOLUTIONS/BeginnerProblem_2.0.c

Here is optimized way to solve the Beginner Problem 2.0

Beginner Problem 2.0 solved in c

---

SOLUTIONS/fizzbuzz.py

Python 3 compaitiable - takes input from STDIN and writes to STDOUT

Add Advanced Fizzbuzz solution (solves #681)

---

SOLUTIONS/Fibonacci.cob

Addition of Fibonacci solution using Cobol language.

Adding cobol solution to fibonacci

---

SOLUTIONS/hello-world-2.py

Solution hello world assignment

Create solution for hello world assignments

---

OPEN CHALLENGE/TopoSort.cpp

C++ code to find lexicographically smallest topological order of a graph(DAG).

added Topological Sorting code in c++

---

SOLUTIONS/GirlFriend.java

closes [#680](https://github.com/hackerearthclub/CODE2RACE/issues/680)

Solution: Bishu and his girlfriend

---

SOLUTIONS/reverse_word.go

```
$ go run SOLUTIONS/reverse_word.go
```

Reverse the text given by user in golang.

---

SOLUTIONS/HelloWorld.pike

Solution of Hello World in pike

---

SOLUTIONS/Compare-Lists.py

Thanks for giving me opportunity to contribute.

CompareLists

---

SOLUTIONS/Hello World.c

basic c programming

---

ASSIGNMENTS/Directions Reduction.md
SOLUTIONS/Directions Reduction.js

I have added Directions Reduction problem with solution as javascript.

Add Directions Reduction problem and solution

---

README.md

Add emoticon

---

SOLUTIONS/Fibonacci.java

Created solution to Fibonacci Series Problem

Fibonacci.java

---

ASSIGNMENTS/ArmstrongNumber.txt

Write a solution in any language

Find An Armstrong Number.

---

SOLUTIONS/largest_palindrome.rb

Added a solution in Ruby programming language to find the [Largest Palindrome number](https://github.com/hackerearthclub/CODE2RACE/blob/master/ASSIGNMENTS/Largest%20Palindrome.md).

A ruby program to find largest palindrome.

---

SOLUTIONS/OctalDecimal

A java program which according to the user choice converts octal to decimal or decimal to octal.

Octal decimal convertor

---

OPEN CHALLENGE/ArrayOperations.cpp

a necessary directoty is missing

one directory is missing

---

ASSIGNMENTS/printPattern.txt

Hi, this is a famous question and i think it should be there in this repository.

New question for pattern

---

FizzBuzz.py
freq.py

This takes the input of range from user....

FizzBuzz.py

---

SOLUTIONS/binary_multiple_of_3

SOLUTION FOR binary mulitple of 3

---

COMPETITORS/competitors.md

Added Ted to Competitors:

---

SOLUTIONS/3rdMax.py

it can be done with less complexity in one pass but this one looks more clean. :) There is a helper function too that can create random array that is not sorted. :)

Not the smallest complexity but elegant way to solve it. 

---

COMPETITORS/competitors.md

Quick fix for contributors file.
* Updates to Contributors to make it look better.
* Made the data structured.
* Added my name.
* Corrected few more lines.
* Removed unnecessary last line.

Added my name and groomed the contributors file.
